### ISSUE TITLE
Can't join a session

### ISSUE THREAD

**Issue by efefury** [saros-project/saros#1145] opened 2021-06-08 16:05 UTC
- OS: [e.g. Windows 10]
 - IDE [e.g. IntellIJ 2021.1.2]
 - Saros Version [e.g. 0.3.0]
 
The error I get while trying to join a session:
```java
java.lang.NoSuchMethodError: 'com.intellij.openapi.module.ModuleType[] com.intellij.openapi.module.ModuleTypeManager.getRegisteredTypes()'
	at saros.intellij.negotiation.hooks.ModuleTypeNegotiationHook.tellClientPreferences(ModuleTypeNegotiationHook.java:79)
	at saros.negotiation.IncomingSessionNegotiation.createClientSessionPreferences(IncomingSessionNegotiation.java:219)
	at saros.negotiation.IncomingSessionNegotiation.accept(IncomingSessionNegotiation.java:152)
	at saros.intellij.ui.wizards.JoinSessionWizard$3.run(JoinSessionWizard.java:112)
	at saros.intellij.ui.wizards.Wizard$2.run(Wizard.java:182)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:545)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:78)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
	```

**Comment by tobous** [comment] 2021-06-08 18:10
Duplicate of #1143.

**Closed by tobous** 2021-06-08 18:10 UTC
Labels: State: Unconfirmed, Type: Bug
