### ISSUE TITLE
Some files in ProjectTree are not checkable

### ISSUE THREAD

**Issue by jafey** [saros-project/saros#151] opened 2018-07-19 13:52 UTC
Some files/checkboxes in the ProjectTree of the HTML StartSessionWizard are not checkable.

To reproduce the issue:

1. run npm dev
2. open "dist/start-session-wizard.html" in your browser
3. open browsers developer console
4. run the code below in the console 
`SarosApi.trigger('updateProjectTrees', [
  {
    "root": {
      "type": "PROJECT",
      "label": "project1",
      "isSelectedForSharing": true,
      "members": [
        {
          "type": "FOLDER",
          "label": "afolder",
          "isSelectedForSharing": true,
          "members": [
            {
              "type": "FILE",
              "label": "afile",
              "isSelectedForSharing": true,
              "members": [],
              "hash": -1316634766
            },
            {
              "type": "FILE",
              "label": "anotherfile",
              "isSelectedForSharing": true,
              "members": [],
              "hash": -532247024
            }
          ],
          "hash": -950491554
        },
        {
          "type": "FOLDER",
          "label": "anotherfolder",
          "isSelectedForSharing": true,
          "members": [
            {
              "type": "FILE",
              "label": "somefile",
              "isSelectedForSharing": true,
              "members": [],
              "hash": -473911617
            }
          ],
          "hash": 715774433
        }
      ],
      "hash": -2049958649
    }
  },
  {
    "root": {
      "type": "PROJECT",
      "label": "project2",
      "isSelectedForSharing": true,
      "members": [
        {
          "type": "FOLDER",
          "label": "somefolder",
          "isSelectedForSharing": true,
          "members": [
            {
              "type": "FILE",
              "label": "randomfile",
              "isSelectedForSharing": true,
              "members": [],
              "hash": -589543344
            }
          ],
          "hash": -991502237
        }
      ],
      "hash": 1692189818
    }
  }
]);`

5. for example "somefile" is not checkable

![image](https://user-images.githubusercontent.com/23552401/42946620-98de1ae2-8b6b-11e8-9add-77b6ebf232bc.png)

**Comment by m273d15** [comment] 2019-02-08 12:21
I was unable to reproduce (all boxes are checkable) this issue
* on windows 10, with:
   * firefox 60.4esr 32-bit
   * ie 11.0.105
   * opera 55.0
* on debian 9.7
   * firefox 60.5esr 64-bit
   * chromium 71.0.3578.80 (dev build)

What is your setup?

**Comment by AbdBarho** [comment] 2019-03-26 17:06
Addressed in #484

**Comment by m273d15** [comment] 2019-10-01 12:00
Closed the issue, because we stopped working on the HTML GUI approach #682

**Closed by m273d15** 2019-10-01 12:00 UTC
Labels: Area: HTML-Frontend
