### ISSUE TITLE
Outdated Information on saros-project.org

### ISSUE THREAD

**Issue by donut87** [saros-project/saros#266] opened 2018-10-15 14:56 UTC
On http://www.saros-project.org/dev-environment-reqs it is stated, that eclipse 3.7 (over 6 years old now) is required. Fortunately, this seems not to be the case. I just ran this with eclipse 4.8.0
```
Version: Photon Release (4.8.0)
Build id: 20180619-1200
```

**Comment by tobous** [comment] 2018-10-15 15:36
Thanks for the notice. A lot of content on the website is outdated. We are currently working on replacing it with github pages. @m273d15 is working on the move and throwing out some of the stuff that is no longer needed (but he is currently a bit preoccupied with the switch to gradle). If you are interested in helping with the new github pages, you can have a chat with him. (I think the current state of the GH pages is in PR #247).

**Comment by donut87** [comment] 2018-10-15 15:37
Thanks for the info. The switch to gradle would definitely address the issue #267 :-)

**Comment by srossbach** [comment] 2018-10-15 15:47
I do not get the problem ? Eclipse 3.7 is required for the developing environment because otherwise the STF is not available. It is up to you if you would like to test your features manually or automatically. Any volunteer who would like to execute the STF regression manually on a weekly schedule ?

**Comment by donut87** [comment] 2018-10-15 15:52
What is there not to get? It is a 6.5 years old IDE and we are requesting developers to install a version of java that went out of public support over 3 years ago. So if STF is the problem, by all means, I can change this ticket to 'Please transfer STF to modern times' (or mark as duplicate and close, if already there).

**Comment by m273d15** [comment] 2019-07-08 14:36
I think this issue is resolved with the migration to eclipse 4.6 and the adjustment of the documentation.

**Closed by m273d15** 2019-07-08 14:36 UTC
Labels: Area: Documentation
