### ISSUE TITLE
Randomly closing Tabs

### ISSUE THREAD

**Issue by Janrupf** [saros-project/saros#740] opened 2019-11-02 18:56 UTC
**Describe the bug**
Sometimes when using Saros tabs of CLion randomly close.

**To Reproduce**
Unknown, seems to happen randomly.

**Expected behavior**
The tabs should not randomly close.

**Log files**
[Both log files in one gist](https://gist.github.com/Janrupf/90df33f26162faec584928c618d8b79f)

**Screenshots**
Not applicable

**Environment (please complete the following information):**
 - OS: Arch Linux
 - IDE CLion 2019.2.5
 - Saros Version: [commit 2249ded2e281d92990747064dd5d20e3c93ea5bd](https://github.com/saros-project/saros/commit/2249ded2e281d92990747064dd5d20e3c93ea5bd)

**Additional context**
I built saros from source to allow it to run in CLion. I don't think its CLion which is causing the trouble here, since everything else seems fine.

**Comment by tobous** [comment] 2019-11-02 19:32
In general, we currently don't support any JetBrains IDEs besides IntelliJ (as there is still enough work to be done completing the base version 😉).

Interesting, I did not now that plugins for IntelliJ had a default compatibility with CLion. I have never done any tests on the platform. As CLion is not open source (and a short search on the topic not yielding any results), I am not sure what the internal differences between the IDEs are, so there might be some CLion specifics that break stuff. Even though all Jetbrains IDEs use the same core, they still differ in some aspects (e.g. we currently can't handle any IDEs not using the module system, PyCharm being an example).

But nice to know that it *generally* seems to work on CLion. 😁

I will have a look at the logs, but I can't promise anything.
Do you recall what you or the other participant were doing around the time the editors closed?
Did you move/delete the resource for the editor, or did the resource still exist and just the editor closed?

**Comment by Janrupf** [comment] 2019-11-02 19:38
Since we are still working on, I can just say that if one editor closes on one side, it also closes for the other side. This is however not true when normally closing them, so I still have no idea what is causing that.

**Comment by tobous** [comment] 2019-11-02 19:43
It seems like the IDE for whatever reason triggered a NOP file move onto the same location ("foo/bar.c" -> "foo/bar.c"), which causes our logic to fail as the target resource already exists. In the process, the old editor is closed. Normally, an editor for the new resource would be opened once it has been created, but the logic fails beforehand.

Adding a workaround for this is quite easy (just dropping moves onto the same resource), but I am still not sure why the issue occurs in the first place.

**Comment by Janrupf** [comment] 2019-11-02 19:47
About supporting CLion, I think you can safely mark it as supported. It pretty much follows all the IntelliJ concepts, including modules.

**Comment by tobous** [comment] 2019-11-02 19:54
I haven't tested it, but https://github.com/saros-project/saros/tree/pr/intellij/drop_nop_moves should fix the issue by adding the mentioned workaround.

So, if you want, you can re-build the plugin on the branch and test it out. 😄

**Comment by tobous** [comment] 2019-11-02 20:17
And if you do use it, an update whether it actually works would be nice. :wink:

**Comment by Janrupf** [comment] 2019-11-02 20:46
Not 100% sure, but it looks like tabs are still closing. Not sure if I installed the plugin correctly, I just kept the old one installed and selected install from disk for the new one.

**Comment by tobous** [comment] 2019-11-02 20:48
Hmm. Could you upload the Saros logs for you and the other participant of one of the new sessions with the patch?

**Comment by Janrupf** [comment] 2019-11-02 20:53
My logs: https://gist.github.com/Janrupf/ce522d8d780f6e92f3d988f55db9952e

**Comment by PublicByte** [comment] 2019-11-02 20:56
Same issue here, these are my logs: https://gist.github.com/PublicByte/4ef167397e946f8621e0308d9304a01a

**Comment by Janrupf** [comment] 2019-11-02 20:57
^ The person I'm working with

**Comment by tobous** [comment] 2019-11-02 21:13
The NOP move issue still occurred on the side of @PublicByte, which means that incorrect activities had to be send by @Janrupf.

Are you sure that you both build the plugin from the branch and installed the new plugin version (and subsequently re-started the IDE to load the new plugin)?

I am not set up for CLion debugging, so getting a better insight into the problem is difficult. I will create a new branch containing some helpful debugging code that should give at least some insight into what is happening (give me a minute). It would be nice if you could try it again using that new version.

**Comment by Janrupf** [comment] 2019-11-02 21:19
Can you also do what it says here? https://github.com/saros-project/saros/blob/master/intellij/resources/META-INF/plugin.xml#L36-L39
Since I had to modify that locally, I want to make sure this it is not because I have old files lying around, which means I want to reclone the repository

**Comment by tobous** [comment] 2019-11-02 21:19
> The NOP move issue still occurred on the side of @PublicByte, which means that incorrect activities had to be send by @Janrupf.
> 
> Are you sure that you both build the plugin from the branch and installed the new plugin version (and subsequently re-started the IDE to load the new plugin)?
> 
> I am not set up for CLion debugging, so getting a better insight into the problem is difficult. I will create a new branch containing some helpful debugging code that should give at least some insight into what is happening (give me a minute). It would be nice if you could try it again using that new version.

Actually, scratch that. The issue is still appearing on both sides. I did not see that the log was truncated for @Janrupf.

**Comment by tobous** [comment] 2019-11-02 21:20
> Can you also do what it says here? https://github.com/saros-project/saros/blob/master/intellij/resources/META-INF/plugin.xml#L36-L39
> Since I had to modify that locally, I want to make sure this it is not because I have old files lying around, which means I want to reclone the repository

Sure. It will be a testing branch anyways.

**Comment by Janrupf** [comment] 2019-11-02 21:21
Ok, thank you. I wont be able to test the changes as soon as you make them directly, I will report back as soon as I can and have tested them.

**Comment by PublicByte** [comment] 2019-11-02 21:23
I won't be able to test your changes either. I'll report back to you asap.

**Comment by tobous** [comment] 2019-11-02 21:38
The new branch is https://github.com/saros-project/saros/tree/test_clion.

I also can just provide the plugin zip for you. I updated the version to `0.2.1.debug` (and made sure that the changes are actually part of the build artifact), so you can also check the version on runtime.
[saros.intellij.debug.zip](https://github.com/saros-project/saros/files/3800967/saros.intellij.debug.zip)

**Comment by tobous** [comment] 2019-11-02 22:42
Ok, I did some testing on my own. The issue occurred for me every time I created a new file. This seems to be fixed with the new workaround.

The previous workaround did not fix the issue as the reported resources moves were re-names onto the same name (and not moves onto the same resource). This is now also covered by the workaround.

I updated the branches as well and here is the new plugin zip if you want to use it directly: 
[saros.intellij.debug.zip](https://github.com/saros-project/saros/files/3801021/saros.intellij.debug.zip)

**Comment by PublicByte** [comment] 2019-11-03 15:19
The issue has been fixed in the new version of your workaround. No files were closed when I and @Janrupf tested it.

**Comment by tobous** [comment] 2019-11-03 15:42
Great.

I also did some more searching around and found the real reason for the issue. Re-parsing of files also triggers the property change listener, providing the "name" property as changed. This lead to the issue as it was interpreted as a re-naming by the Saros logic.

But there is an experimental method that checks for this situation which allows for a much cleaner solution.

**Comment by tobous** [comment] 2019-11-03 16:52
I created #741 as an official fix for this issue.

As pointed out in https://github.com/saros-project/saros/pull/741/commits/2a1c4694b21a71e3ba5bab54f07c3df3473958a4, I am currently against enabling compatibility for other JetBrains IDEs. For now, guaranteeing compatibility and checking for implementation differences increases the testing effort by too much, especially since the plugin itself still needs a lot of work. But I will also discuss this topic with some of the other Saros developers.

But this only means that that we won't provide official build (for now). You can still build it yourself.

**Comment by Janrupf** [comment] 2019-11-04 18:02
Maybe there should be some option when building with gradle to enable compatibility with a big disclaimer that this is not officially supported. But for example, for Clion it seems to work without any issues. (Only test CMake projects yet tho)

**Comment by tobous** [comment] 2019-11-04 18:57
I don't know whether that is possible. As far as I know, the compatibility is determined through the presence of an entry in the `plugin.xml` file for the plugin (see [doc](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html). And I couldn't find any other way of enabling/disabling the compatibility.

We use the [gradle intellij plugin](https://github.com/JetBrains/gradle-intellij-plugin) to build. It has the capabilities to [modify the plugin.xml on build](https://github.com/JetBrains/gradle-intellij-plugin#patching-dsl), but the `<depends>...</depends>` tags don't seem to be part of the fields that can be modified.

**Comment by tobous** [comment] 2019-11-05 02:51
But if you find a way, we are open to suggestions 😉

**Closed** 2019-11-11 15:29 UTC
Labels: Area: IntelliJ, Aspect: User Experience, Type: Bug
