### ISSUE TITLE
Not connected issue

### ISSUE THREAD

**Issue by Retrooper** [saros-project/saros#891] opened 2020-04-01 10:32 UTC
Whenever I try connecting to my account, it still displays me I am not connected.
I don't see my contacts, ect…
I am using IntelliJ and the latest released Saros version, I believe 0.2.2 or so.

I click on the bottom right Saros icon, click on the connect button, it says Connecting.... and then just stops and does not display me connected.

I'd expect to be connected and see all my contacts.

I do not think a screenshot is needed, what should I screenshot? 
It just behaves like I have never clicked connected, btw I am unsure if this is normal, but I see two Saros icons on the left side after opening the saros icon on the bottom right.

 - OS:  Windows 10
 - IDE  IntelliJ IDEA 2019.1.3
 - Saros Version 0.2.2? the latest for IntelliJ

Please help me as soon as possible. Or describe why it is not working.
I hope I am not making some dumb mistake, I have used Saros before on other machines and it worked...

**Comment by tobous** [comment] 2020-04-01 13:01
This sound to me like the plugin fails to conntect to the XMPP server due to some issues with the account (either because the server could not be reached or the username or password is not correct).  We currently don't have any user notifications for such cases (I know this isn't the best usability practice, but UI stuff still has a relatively low priority at this stage). Will see what I can do to improve the usability (e.g. by implementing a user notification that the connection failed).

This should be mentioned in the log files, so could you provide the log files of such a connection attempt? Where to find the log files is described [here](https://www.saros-project.org/documentation/getting-started.html?tab=intellij#report-a-bug).

In the meantime, you can try re-adding your account to the account store to make sure that this isn't an issue with the username or password. To do so, you can  follow the guide given on our [website](https://www.saros-project.org/documentation/getting-started.html?tab=intellij#adding-an-xmpp-account).

**Comment by m273d15** [comment] 2020-04-01 13:17
I faced a similar issue today, but I assumed that it would be caused by my bad wifi connection. Probably, we should check the xmpp server.

**Comment by Retrooper** [comment] 2020-04-01 13:19
Well sadly for 6 hours I was trying to fix this and had no idea, I thought it was my computer, I recently got a new computer and I was so confused...

**Comment by tobous** [comment] 2020-04-01 13:43
> I faced a similar issue today, but I assumed that it would be caused by my bad wifi connection. Probably, we should check the xmpp server.

The server works fine for me right now (and the activity on the machine the server is running on also looked normal; it's not particularly busy). So maybe there was a temporary issue this morning for whatever reason, but it should work right now.

@Retrooper So if the issue still persists for you, it should be unrelated to our server. (It could, however, still be related to your connection to the server, i.e. due to a firewall, etc.). Have you tried re-adding you account making sure that the user name and password are typed in correctly?

**Comment by tobous** [comment] 2020-04-01 16:16
The usability issue will be addressed by #893.

@Retrooper Please supply some log files if the issue still persists for you.

Otherwise, I would see this issue as resolved.

**Comment by Retrooper** [comment] 2020-04-01 16:17
I am unable to test this untill tomorrow on my computer.

**Comment by tobous** [comment] 2020-04-01 16:29
> I am unable to test this untill tomorrow on my computer.

No worries, this isn't urgent. ☺️ Just want to make sure that everything is sorted out correctly and that, if there still is an issue, we find it so that we can address it.

**Comment by Retrooper** [comment] 2020-04-02 11:20
My account didn’t work, so I just created a new one

**Comment by tobous** [comment] 2020-04-02 11:32
And it now works with the new one?

**Comment by Retrooper** [comment] 2020-04-02 11:32
Yup

**Closed** 2020-04-02 11:34 UTC
Labels: Area: IntelliJ, Aspect: Network, State: Unconfirmed, Type: Bug
